# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-04 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cathedra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=200)),
                ('d_cathedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univer.Cathedra')),
            ],
        ),
        migrations.CreateModel(
            name='HomeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ht_name', models.CharField(max_length=200)),
                ('accomplished', models.BooleanField(default=False)),
                ('ht_disciplin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univer.Disciplin')),
            ],
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_name', models.CharField(max_length=20)),
                ('l_las_name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20)),
                ('s_las_name', models.CharField(max_length=35)),
                ('s_email', models.EmailField(max_length=254)),
                ('s_phone', models.PositiveIntegerField()),
                ('s_cathedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univer.Cathedra')),
                ('s_disciplins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univer.Disciplin')),
                ('s_ht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univer.HomeTask')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=200)),
                ('u_city', models.CharField(max_length=200)),
                ('u_uri', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='s_university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univer.University'),
        ),
        migrations.AddField(
            model_name='lector',
            name='l_students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univer.Student'),
        ),
    ]
