# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-04 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0002_auto_20161104_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathedra',
            name='c_univer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='univer.University'),
        ),
        migrations.AlterField(
            model_name='disciplin',
            name='d_cathedra',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='univer.Cathedra'),
        ),
        migrations.AlterField(
            model_name='lector',
            name='l_cathedra',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='univer.Cathedra'),
        ),
        migrations.AlterField(
            model_name='lector',
            name='l_students',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='univer.Student'),
        ),
        migrations.AlterField(
            model_name='lector',
            name='l_univer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='univer.University'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_cathedra',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='univer.Cathedra'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_disciplins',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='univer.Disciplin'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_ht',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='univer.HomeTask'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_university',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='univer.University'),
        ),
    ]
