# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-04 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0005_remove_cathedra_cat_univer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cathedra',
            name='cat_univer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='univer.University'),
        ),
    ]
