# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-04 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0007_auto_20161104_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cathedra',
            old_name='cat_name',
            new_name='c_name',
        ),
        migrations.RenameField(
            model_name='cathedra',
            old_name='cat_univer',
            new_name='c_univer',
        ),
    ]
