# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0008_auto_20161104_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lector',
            name='l_cathedra',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cathedras', to='univer.Cathedra'),
        ),
        migrations.AlterField(
            model_name='lector',
            name='l_students',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='univer.Student'),
        ),
        migrations.AlterField(
            model_name='lector',
            name='l_univer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='univer.University'),
        ),
    ]
