# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0009_auto_20161107_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_disciplins',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='disciplins', to='univer.Disciplin'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_ht',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hometasks', to='univer.HomeTask'),
        ),
    ]
