# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0010_auto_20161107_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lector',
            name='l_students',
        ),
        migrations.AddField(
            model_name='student',
            name='s_lector',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='univer.Lector'),
        ),
    ]
